from __future__ import absolute_import
from .normals import CholNormal
from .normals import DiagNormal
from .util import tri_vec_shape
from .util import ceil_divide
from .util import get_flags
from .util import log_cholesky_det
from .util import diag_mul
from .util import init_list
from .util import logsumexp
from .util import mat_square
